
### GET sans params
GET http://localhost:3000/api/toto
Content-type : application/json

### POST 
POST http://localhost:3000/api/toto
Content-type : application/json

{
    "name": "Sabrina"
}

###GET avec params
GET http://localhost:3000/api/toto/3
Content-type : application/json

###



###GET avec element
POST http://localhost:3000/api/toto
Content-type : application/json

{
    "data": {
        "name": "Sabrina"
    }
}
###



###POST avec element
POST http://localhost:3000/api/qcm
Content-type : application/json

{
    "data": {
        "title": "Choux ou brocoli"
    }
}
###

###GET de tous les qcm
GET http://localhost:3000/api/qcms
Content-type : application/json

###

###GET de tous les qcm
GET http://localhost:3000/api/qcm/1
Content-type : application/json

###

###POST question
POST http://localhost:3000/api/questions
Content-type : application/json

{
    "data": {
        "content": "Quel légume est souvent utilisé pour faire des smoothies verts ?",
        "qcmId":1
    }
}
###
###GET de tous les question
GET http://localhost:3000/api/qcms/1/
Content-type : application/json

###

###GET de la question
PUT  http://localhost:3000/api/qcms
Content-type : application/json


### POST choice
POST  http://localhost:3000/api/choices
Content-type : application/json

{
    "data": {
        "isCorrect": false, 
        "response": "Chou romanesco",
        "questionId":3
    }
}

### PUT choice
PUT  http://localhost:3000/api/choices/7
Content-type : application/json

{
    "data": {
        "response": "Patate douce",
        "isCorrect": false,
        "questionId": 2
    }
}


### GET choice
GET  http://localhost:3000/api/choices
Content-type : application/json


